permalink: /:month-:day-:year/:title.html

# Theme settings
theme:

  # Site name
  site_name: cat @abulte > weblog
  alt_tile: Blog d'Alexandre Bulté

  # Google analytics UID
  google_analytics_uid: UA-34672109-2

  # Disqus shortname, for comments
  disqus_shortname: bulte

  # Number of featured posts on homepage
  homepage_featured: 3

  # Number of posts on homepage (in addition to featured posts)
  homepage_posts: 5

  # Number of words to display in post summaries
  featured_wordcount: 40

google_plus_url: https://plus.google.com/110826034342222404990?rel=author

markdown: redcarpet2

redcarpet:
  extensions: ["strikethrough"]
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]